name: CI
on:
  workflow_dispatch:

jobs:
  Alpine:
    strategy:
      matrix:
        php-version:
          - "8.0-cli-alpine3.16"
          - "8.1-cli-alpine3.19"
          - "8.2-cli-alpine3.19"
          - "8.3-cli-alpine3.19"
          - "8.4-cli-alpine3.19"
          - "8.5-cli-alpine3.22"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build and test extension"
        run: "docker build -t simdjsontest -f docker-alpine --build-arg BASE_IMAGE=${{ matrix.php-version }} ."

      - name: "Show info"
        run: "docker run --rm simdjsontest php --ri simdjson"

  Ubuntu-dev:
    strategy:
      matrix:
        php-version:
          - "8.2.30"
          - "8.3.30"
          - "8.4.17"
          - "8.5.2"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build PHP and extension in development mode"
        run: "docker build -f docker-dev --build-arg PHP_VERSION=${{ matrix.php-version }} ."

  Ubuntu:
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
        experimental: [false]
    runs-on: ${{ matrix.os }}
    name: PHP ${{ matrix.php-version }} Test on ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: json
          # for correct php-config extension dir, see https://github.com/shivammathur/setup-php/issues/147
          tools: pecl, phpize, php-config

      - name: Build extension
        run: |
          export NO_INTERACTION=true
          export REPORT_EXIT_STATUS=1
          export SIMDJSON_HIGH_MEMORY_TESTS=1
          php-config --extension-dir
          phpize
          ./configure
          make -j$(nproc)
          sudo make install
          make test TESTS="--show-diff -j2 -q" || exit 1

      - name: Show
        run: "php -dextension=simdjson.so --ri simdjson"

      - name: Error log
        if: ${{ failure() }}
        run: "ls -1t tests/*.log | xargs -d'\n' cat"

      - name: Error diff
        if: ${{ failure() }}
        run: |
          for FILE in $(find tests -name '*.diff'); do
            echo $FILE
            cat $FILE
            echo
          done

  Macos:
    runs-on: macos-latest
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        php: ['8.0', '8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json
          coverage: none
          tools: none

      - name: Build simdjson
        run: |
          phpize
          ./configure
          make -j$(nproc)

      - name: Run tests
        run: |
          export SIMDJSON_HIGH_MEMORY_TESTS=1
          make test TESTS="--show-diff -j2 -q"
